name: On Scheduled

on:
  schedule:
    - cron: "0 21 * * 2"

jobs:
  build:
    uses: ./.github/workflows/job-build-image.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
